name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller mcrcon python-dotenv discord.py flask

    - name: Build exe with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --name arkshopbot \
          --add-data "shop_items.json;." \
          --add-data "db.py;." \
          --add-data ".env.example;.env" \
          "Discord Shop System.py"

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: arkshopbot-windows
        path: dist/arkshopbot.exe
