name: Build exe with PyInstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller mcrcon python-dotenv discord.py flask aiolimiter
          
      - name: Build GUI launcher EXE
        shell: bash
        run: |
          pyinstaller --onefile --windowed \
            --name arkshopbot_gui \
            --icon logo_icon.ico \
            arkshopbot_launcher.py



      - name: Upload GUI Launcher Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arkshopbot-gui-windows
          path: dist\arkshopbot_gui.exe
